### ISSUE TITLE
Hwid Spoofer问题

### ISSUE THREAD

**Issue by Jwnd4** [VapuClient/Cheart-Issue-Tracker#23]
1.Hwid spoofer会调用WMIC 但由于Windows10 没有WMIC 所以Hwid spoofer会失效
2.启动游戏之后便会出现调用WMIC失败的提示（在cmd里）
3.1.18.1
4.以下为错误报告:??? ?? ???? ?????: \Device\HarddiskVolume5\PC4399_MCLDownload\ext\jre-v64-220420\jdk17\bin\javaw.exe (1888)
java.io.IOException: Cannot run program "wmic": CreateProcess error=2, 系统找不到指定的文件。
        at java.base@17.0.8/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base@17.0.8/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at java.base@17.0.8/java.lang.Runtime.exec(Runtime.java:594)
        at java.base@17.0.8/java.lang.Runtime.exec(Runtime.java:418)
        at java.base@17.0.8/java.lang.Runtime.exec(Runtime.java:315)
        at com.heypixel.Main.getArgs(Main.java:292)
        at com.heypixel.Main.onThreadLoop(Main.java:266)
        at com.heypixel.Main.lambda$main$1(Main.java:217)
        at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:179)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:889)
        at java.base@17.0.8/java.lang.ProcessImpl.create(Native Method)
        at java.base@17.0.8/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
        at java.base@17.0.8/java.lang.ProcessImpl.start(ProcessImpl.java:158)
        at java.base@17.0.8/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 10 more
5.是的 我使用了最新的客户端

**Comment by mckuhei** [comment]
WMIC一直包含在系统里，使用一键Ghost导致的
